version: 2

jobs:
  test:
    docker:
      - image: golang:1.15-buster
        environment:
          SPANNER_EMULATOR_HOST: localhost:9010
          SPANNER_EMULATOR_HOST_REST: localhost:9020
          PROJECT: yo-test
          INSTANCE: yo-test
          DATABASE: yo-test
      - image: gcr.io/cloud-spanner-emulator/emulator:1.2.0
    working_directory: /go/src/github.com/cloudspannerecosystem/yo/v2
    steps:
      - checkout:
          path: /go/src/github.com/cloudspannerecosystem/yo

      - run:
          name: install deps
          command: |
            make deps

      - run:
          name: build
          command: |
            make build

      - run:
          name: regenerate templates and check diff
          command: |
            make regen
            git diff --quiet module/builtin/tplbin/

      - run:
          name: regenerate template files and check diff
          command: |
            make recreate-templates YOBIN=./yo
            git diff --quiet module/builtin/templates/

      - run:
          name: run integration test
          command: |
            make test

      - run:
          name: regenerate testdata-from-ddl and check diff
          command: |
            make testdata-from-ddl YOBIN=./yo
            git diff --quiet test/

      - run:
          name: regenerate testdata and check diff
          command: |
            make testdata YOBIN=./yo
            git diff --quiet test/

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
