version: 2.1

jobs:
  test:
    docker:
      - image: golang:1.23-bullseye
        environment:
          SPANNER_EMULATOR_HOST: localhost:9010
          SPANNER_EMULATOR_HOST_REST: localhost:9020
          PROJECT: yo-test
          INSTANCE: yo-test
          DATABASE: yo-test
      - image: gcr.io/cloud-spanner-emulator/emulator:1.5.36
    working_directory: /go/src/github.com/cloudspannerecosystem/yo
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            make deps

      - run:
          name: build
          command: |
            make build

      - run:
          name: regenerate templates and check diff
          command: |
            set -x
            go-assets-builder -help
	        rm tplbin/templates.go
	        go-assets-builder --package=tplbin --strip-prefix="/templates/" --output tplbin/templates.go templates/*.tpl
            make regen
            git diff --quiet tplbin/

      - run:
          name: regenerate testdata-from-ddl and check diff
          command: |
            make testdata-from-ddl YOBIN=./yo
            git diff --quiet test/

      - run:
          name: regenerate template files and check diff
          command: |
            make recreate-templates YOBIN=./yo
            git diff --quiet templates/

      - run:
          name: run integration test
          command: |
            make test

      - run:
          name: regenerate testdata and check diff
          command: |
            make testdata YOBIN=./yo
            make check-diff

  v2test:
    docker:
      - image: golang:1.23-bullseye
        environment:
          SPANNER_EMULATOR_HOST: localhost:9010
          SPANNER_EMULATOR_HOST_REST: localhost:9020
          PROJECT: yo-test
          INSTANCE: yo-test
          DATABASE: yo-test
      - image: gcr.io/cloud-spanner-emulator/emulator:1.5.34
    working_directory: /go/src/github.com/cloudspannerecosystem/yo
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            make -C v2 deps

      - run:
          name: build
          command: |
            make -C v2 build

      - run:
          name: regenerate template files and check diff
          command: |
            make -C v2 recreate-templates YOBIN=./yo
            git diff --quiet v2/module/builtin/templates/

      - run:
          name: run integration test
          command: |
            make -C v2 test

      - run:
          name: regenerate testdata-from-ddl and check diff
          command: |
            make -C v2 testdata-from-ddl YOBIN=./yo
            git diff --quiet test/

      - run:
          name: regenerate testdata and check diff
          command: |
            make -C v2 testdata YOBIN=./yo
            make -C v2 check-diff
  check_lint:
    docker:
      - image: golang:1.23-bullseye
    working_directory: /go/src/github.com/cloudspannerecosystem/yo
    steps:
      - checkout
      - run:
          name: check lint
          command: |
            make check_lint
  check_go_mod:
    docker:
      - image: golang:1.23-bullseye
    working_directory: /go/src/github.com/cloudspannerecosystem/yo
    steps:
      - checkout
      - run:
          name: check go mod
          command: |
            make check_gomod

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
      - v2test
      - check_lint
      - check_go_mod
